title = "小瑜的部落格"
baseURL = "https://doudouu0504.github.io/"
theme = "ananke"
resourceDir = "resources"

defaultContentLanguage = "zh"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 6 # this is set low for demonstrating with dummy content. Set to a higher number

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params] #
text_color = ""
author = ""
favicon = ""
site_logo = "images/大頭貼.png"
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 4
custom_css = ["css/custom.css"]

[params.ananke.social.share]
networks = [
  "email",
  "facebook",
  "youtube",
  "instagram",
]

[params.ananke.social.follow]
networks = [
  "instagram",
  "youtube",
  "facebook",
]

[params.ananke.social.facebook]
username = "邱佳瑜"
profilelink = "https://www.facebook.com/doudouu0504/"

[params.ananke.social.email]
username = "邱佳瑜"
profilelink = "mailto:selinafs880504@gmail.com"

[params.ananke.social.instagram]
username = "doudouu_photos"
profilelink = "https://www.instagram.com/doudouu_photos/"

[params.ananke.social.youtube]
username = "UU-Music Channel"
profilelink = "https://www.youtube.com/@uu-musicchannel7080"
 


[markup] #這個是處理html的內容
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu] #這個是navbar的連結
  [[menu.main]]
    name = "posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 3
